import type { Lang } from "@/lib/strings";

export const signupStrings = {
  en: {
    back: "Back",
    badge: "LiveAssist workspace",
    authTitle: "Start with your work account",
    authBody: "One secure sign-in. Setup takes about a minute.",
    google: "Continue with Google",
    retry: "Try again",
    authError: "Google sign-in did not finish. Check your connection and try again.",
    authMissing: "Authentication is not configured. Add the Supabase public variables to continue.",
    databaseMissing: "Signup database is not ready. Apply supabase/signup.sql, then try again.",
    legalPrefix: "By continuing, you agree to our",
    privacy: "Privacy Policy",
    terms: "Terms",
    and: "and",
    modeTitle: "How would you like to start?",
    modeBody: "Choose one path. You can connect more tools later.",
    realTitle: "Connect my CRM",
    realBody: "Set up a workspace and connect your team data.",
    demoTitle: "Try the demo",
    demoBody: "Explore LiveAssist with safe test data and no CRM connection.",
    demoLoading: "Preparing your demo…",
    companyTitle: "Tell us only what we need",
    companyBody: "Four quick choices, then your workspace is ready.",
    companyName: "Company name",
    companyPlaceholder: "Acme Support",
    managers: "Number of managers",
    crm: "CRM",
    goal: "Primary goal",
    continue: "Create workspace",
    saving: "Creating workspace…",
    sales: "Sales",
    support: "Customer support",
    training: "Team training",
    other: "Other",
    noCrm: "No CRM yet",
    companyNameShort: "Enter at least 2 characters.",
    companyNameLong: "Keep the name under 120 characters.",
    required: "Choose one option.",
    submitError: "We could not create the workspace. Your choices are saved — try again.",
    completeEyebrow: "Workspace ready",
    completeTitle: "You’re ready for LiveAssist",
    // The name-prefixed variant is its own string, not a lowercased
    // completeTitle: lowercasing the whole sentence also lowercased the brand
    // ("ready for liveassist").
    completeTitleNamed: "you’re ready for LiveAssist",
    completeDemo: "Demo workspace",
    completeReal: "Company workspace",
    crmLabel: "CRM status",
    pending: "Selected — connection pending",
    unsupported: "Choice saved",
    connected: "Connected",
    demo: "Safe demo data",
    failed: "Connection needs attention",
    open: "Open LiveAssist",
    opening: "Opening LiveAssist…",
    openedHint: "LiveAssist should be signing you in. Nothing happened? Come back and press the button again.",
    handoffError: "We could not create a sign-in link. Press the button again.",
    desktopFinishTitle: "Finish in the desktop app",
    desktopFinishBody: "Open LiveAssist and press “Sign in to start”. For your safety, the app only accepts a sign-in it started itself.",
    download: "Download the desktop app",
    handoffNote: "The sign-in link is single-use and expires in a few minutes. It never carries your session tokens.",
    languageLabel: "Language",
  },
  ru: {
    back: "Назад",
    badge: "Workspace LiveAssist",
    authTitle: "Начните с рабочего аккаунта",
    authBody: "Один безопасный вход. Настройка займёт около минуты.",
    google: "Продолжить с Google",
    retry: "Попробовать снова",
    authError: "Вход через Google не завершён. Проверьте соединение и попробуйте снова.",
    authMissing: "Авторизация не настроена. Добавьте публичные переменные Supabase.",
    databaseMissing: "База регистрации не готова. Примените supabase/signup.sql и попробуйте снова.",
    legalPrefix: "Продолжая, вы соглашаетесь с",
    privacy: "Политикой конфиденциальности",
    terms: "Условиями",
    and: "и",
    modeTitle: "С чего хотите начать?",
    modeBody: "Выберите один сценарий. Остальные инструменты можно подключить позже.",
    realTitle: "Подключить мою CRM",
    realBody: "Настройте рабочее пространство и подключите данные вашей команды.",
    demoTitle: "Попробовать демо",
    demoBody: "Посмотрите LiveAssist на безопасных тестовых данных без подключения CRM.",
    demoLoading: "Готовим демо…",
    companyTitle: "Только самое необходимое",
    companyBody: "Четыре коротких выбора — и workspace готов.",
    companyName: "Название компании",
    companyPlaceholder: "Acme Support",
    managers: "Количество менеджеров",
    crm: "CRM",
    goal: "Основная цель",
    continue: "Создать workspace",
    saving: "Создаём workspace…",
    sales: "Продажи",
    support: "Поддержка клиентов",
    training: "Обучение команды",
    other: "Другое",
    noCrm: "Пока нет CRM",
    companyNameShort: "Введите минимум 2 символа.",
    companyNameLong: "Название должно быть короче 120 символов.",
    required: "Выберите один вариант.",
    submitError: "Не удалось создать workspace. Выбор сохранён — попробуйте снова.",
    completeEyebrow: "Workspace готов",
    completeTitle: "Всё готово к работе",
    completeTitleNamed: "всё готово к работе",
    completeDemo: "Демо-workspace",
    completeReal: "Workspace компании",
    crmLabel: "Статус CRM",
    pending: "Выбрано — подключение ожидается",
    unsupported: "Выбор сохранён",
    connected: "Подключено",
    demo: "Безопасные демо-данные",
    failed: "Подключение требует внимания",
    open: "Открыть LiveAssist",
    opening: "Открываем LiveAssist…",
    openedHint: "LiveAssist сейчас выполнит вход. Ничего не произошло? Вернитесь и нажмите кнопку ещё раз.",
    handoffError: "Не удалось создать ссылку для входа. Нажмите кнопку ещё раз.",
    desktopFinishTitle: "Завершите вход в приложении",
    desktopFinishBody: "Откройте LiveAssist и нажмите «Войдите, чтобы начать». В целях безопасности приложение принимает только тот вход, который начало само.",
    download: "Скачать desktop-приложение",
    handoffNote: "Ссылка для входа одноразовая и действует несколько минут. Токенов сессии в ней нет.",
    languageLabel: "Язык",
  },
} as const satisfies Record<Lang, Record<string, string>>;
